#define BUILD_VERSION "0.0.2"
#define DEBUG_BUILD 0
#define CAMERA_OFFSET make_float3(0, 0, 0)
#define VOXEL_SIZE_IN_METERS 0.1f
#define INVERSE_VOXEL_SIZE_IN_METERS (1.0f / (float)VOXEL_SIZE_IN_METERS)
#define VOXEL_SIZE_IN_METERS_SQR (VOXEL_SIZE_IN_METERS*VOXEL_SIZE_IN_METERS)
#define DEFAULT_CANVAS_HEIGHT 128
#define DEFAULT_CANVAS_WIDTH 128
#define DEFAULT_ERASER_SIZE 4
#define BACKUP_FILE_TIME_SECONDS 2
#define MAX_DROPPED_FILES 128
#define MAX_FRAMES_AFTER_EVENT_TO_RUN 20
#define DEFINED_APP_NAME "Spixl"
#define DEFINED_FILE_NAME "spixl"