#define DEBUG_BUILD 1
#define CAMERA_OFFSET make_float3(0, 0, 0)
#define VOXEL_SIZE_IN_METERS 0.1f
#define INVERSE_VOXEL_SIZE_IN_METERS (1.0f / (float)VOXEL_SIZE_IN_METERS)
#define VOXEL_SIZE_IN_METERS_SQR (VOXEL_SIZE_IN_METERS*VOXEL_SIZE_IN_METERS)
#define DEFAULT_CANVAS_HEIGHT 128
#define DEFAULT_CANVAS_WIDTH 128
#define DEFAULT_ERASER_SIZE 4
#define BACKUP_FILE_TIME 60 //NOTE: Every 1 minute
#define MAX_DROPPED_FILES 128