#define GRAVITY_POWER 28
#define JUMP_POWER 6
#define MAX_SHAKE_TIMER 0.4f
#define EPSILON_VALUE 0.2f
#define WALK_SPEED 2
#define CIRCLE_RADIUS_MAX 10
#define SHOW_CIRCLE_DELAY 2
#define STAMINA_DRAIN_SPEED 0.1f
#define STAMINA_RECHARGE_SPEED 0.1f
#define CLOUD_EVELVATION 100 //NOTE: This is 192 in actual minecraft - Clouds always float westward between layer 192 and 196
#define WATER_ELEVATION 40 //NOTE: This is 62 in actual minecraft
#define BLOCK_SIZE 1 
#define AO_BIT_NOT_VISIBLE 61
#define AO_BIT_CREATING 62
#define AO_BIT_INVALID 63
#define SUB_SOIL_DEPTH 5
#define DISTANCE_CAN_PLACE_BLOCK 6 //NOTE: Minecraft has a reach distance of 5 in survival and 6 in creative
#define CAMERA_OFFSET make_float3(0, 0, 0)
#define ITEM_PER_SLOT_COUNT 64
#define ITEM_HOT_SPOTS 8
#define VOXEL_SIZE_IN_METERS 0.1f
#define INVERSE_VOXEL_SIZE_IN_METERS (1.0f / (float)VOXEL_SIZE_IN_METERS)
#define VOXEL_SIZE_IN_METERS_SQR (VOXEL_SIZE_IN_METERS*VOXEL_SIZE_IN_METERS)
#define VOXELS_PER_METER 10
#define MAX_CONTACT_POINTS_PER_PAIR 64
#define PHYSICS_VELOCITY_SLEEP_THRESHOLD 0.1 //NOTE: Box2d is 0.05
#define PHYSICS_SLEEP_TIME_THRESHOLD 0.5 //NOTE: Seconds
#define PHYSICS_RESTITUTION_VELOCITY_THRESHOLD 0.1f //NOTE: metres per Seconds
#define PHYSICS_RESTITUTION_VELOCITY_THRESHOLD_SQR (PHYSICS_RESTITUTION_VELOCITY_THRESHOLD*PHYSICS_RESTITUTION_VELOCITY_THRESHOLD)
#define BOUNDING_BOX_MARGIN 0.3f
#define USE_EDGES_FOR_COLLISION 0

//NOTE: DEBUGGING CONSTANTS
#define PERLIN_SIZE 128
#define MAX_BONES_PER_MODEL 1000